name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT
<<<<<<< HEAD
        run: java -jar ./artifacts/app-ibank.jar -P:profile=test &
      - name: Build with Gradle
        run: ./gradlew test -Dselenide.headless=true --info
=======
        run: java -jar ./artifacts/app-ibank.jar -P:profile=test -port=7777 &
      - name: Build with Gradle
        run: ./gradlew test --info -Dselenide.headless=true
>>>>>>> 1fc3c0fe2117e4a86bbbb7a21b95f0067ad275ed
